chore: replace heptio/contour with project contour
heptiolabs/gangway pull request #184
Opened 2021-04-05 14:10 UTC by kushthedude

Signed-off-by: kushthedude <kushthedude@gmail.com>
fixes https://github.com/projectcontour/contour/issues/2966

2021-04-05 14:28 UTC, sunjayBhatia requested changes
Looks good to me, just one wording change to make the sentences flow a bit better

2021-04-05 14:28 UTC, sunjayBhatia commented on docs/README.md
> +See [Project Contour's Guide](https://projectcontour.io/guides/cert-manager/) for help in getting started with Contour.
```suggestion
See [this guide](https://projectcontour.io/guides/cert-manager/) for help getting started.
```

2021-04-06 05:06 UTC, youngnick approved these changes
LGTM with @sunjayBhatia's requested change.

2021-04-07 20:26 UTC, kushthedude commented
Hi @youngnick @sunjayBhatia I have did the requested changes, please review

2021-04-07 22:10 UTC, sunjayBhatia approved these changes

2021-04-07 22:11 UTC, sunjayBhatia commented
Ah, I don't have official powers in this org, so someone else will have to approve officially

2021-06-08 19:11 UTC, stevesloka approved these changes
/lgtm 🎉

2021-06-08 19:11 UTC, merged